version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - nilerr
    - prealloc

  settings:
    misspell:
      locale: US

  exclusions:
    paths:
      - tests
      - vendor

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes: github.com/kovey/kow
