run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - nilerr
    - prealloc
    - reassign

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/kovey/kow
  prealloc:
    simple: true
    for-loops: true

issues:
  exclude-dirs:
    - tests
    - vendor
  exclude-files:
    - ".*_test\\.go$"
    - "tests/.*"
