version: 3.0

etcd:
  endpoints:
    - 127.0.0.1:2345
  timeout: 30
  username: root
  password: root
  namespace: default
listen:
  host: 0.0.0.0
  port: 8080
app:
  time_zone: Asia/Shanghai
  pprof_open: On
